---
- name: Install general stuffs
  pacman:
    name: ["xorg-server", "i3-gaps", "lightdm", "lightdm-webkit2-greeter", "git", "ansible", "alacritty", "base-devel", "nvidia"]
    state: present
  become: yes

- name: Ensure lightdm uses webkit2-greeter
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#?greeter-session='
    line: greeter-session=lightdm-webkit2-greeter
  become: yes

- name: Ensure lightdm uses i3
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#?user-session='
    line: user-session=i3
  become: yes

- name: Start lightdm
  service:
    name: lightdm
    enabled: true
    state: started
  become: yes

# https://wiki.archlinux.org/index.php/NVIDIA#DRM_kernel_mode_setting
- name: Add nvidia-drm.modeset=1 kernel parameter
  copy:
    content: |
      options nvidia_drm modeset=1
    dest: /etc/modprobe.d/nvidia.conf
  become: yes

- name: Add to initramfs
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES=()'
    line: 'MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)'
  become: yes
  register: add_mod

- name: Run mkinitcpio
  command: "mkinitcpio -p linux"
  when: add_mod.changed
  become: yes

- name: Create Pacman hook directory
  file:
    path:   /etc/pacman.d/hooks
    state: directory
  become: yes

- name: Create Pacman hook
  template:
    src:    nvidia.hook.j2
    dest:   /etc/pacman.d/hooks/nvidia.hook
    backup: no
  become: yes

# https://wiki.archlinux.org/index.php/Solid_state_drive#Periodic_TRIM
- name: "Start periodic trim: fstrim.service"
  service:
    name: fstrim.service
    enabled: true
  become: yes

# https://wiki.archlinux.org/index.php/Solid_state_drive#Periodic_TRIM
- name: "Start periodic trim: fstrim.timer"
  service:
    name: fstrim.timer
    enabled: true
    state: started
  become: yes

- name: Sound
  pacman:
    name: ["alsa-utils", "pulseaudio", "pulseaudio-alsa"]
    state: present
  become: yes

- name: Enable systemd-timesyncd
  service:
    name: systemd-timesyncd
    enabled: true
    state: started
  become: yes

- name: Install fonts
  pacman:
    name:
      - tex-gyre-fonts
      - ttf-liberation
      - noto-fonts-cjk
      - noto-fonts-emoji
    state: present
  become: yes

- name: Enable multilib (for steam)
  replace:
    path: /etc/pacman.conf
    regexp: '^#\[multilib\]\n^#Include.*'
    replace: |-
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  become: yes

- name: Disable power key on HHKB
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^HandlePowerKey=.*'
    line: 'HandlePowerKey=ignore'
  become: yes
